-- Product Seed Data for D1
-- Run with: npx wrangler d1 execute grocery_db --file=seed/products.sql

INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (1, '白菜', 'Chinese Cabbage', '🥬', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (2, '西兰花', 'Broccoli', '🥦', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (3, '菠菜', 'Spinach', '🥬', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (4, '番茄', 'Tomato', '🍅', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (5, '黄瓜', 'Cucumber', '🥒', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (6, '胡萝卜', 'Carrot', '🥕', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (7, '土豆', 'Potato', '🥔', 'vegetables', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (8, '洋葱', 'Onion', '🧅', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (9, '大蒜', 'Garlic', '🧄', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (10, '青椒', 'Green Pepper', '🫑', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (11, '茄子', 'Eggplant', '🍆', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (12, '芹菜', 'Celery', '🥬', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (13, '生菜', 'Lettuce', '🥬', 'vegetables', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (14, '玉米', 'Corn', '🌽', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (15, '蘑菇', 'Mushroom', '🍄', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (16, '豆角', 'Green Beans', '🫛', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (17, '南瓜', 'Pumpkin', '🎃', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (18, '花菜', 'Cauliflower', '🥦', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (19, '韭菜', 'Chinese Chives', '🥬', 'vegetables', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (20, '莲藕', 'Lotus Root', '🥬', 'vegetables', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (21, '山药', 'Chinese Yam', '🥔', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (22, '豆芽', 'Bean Sprouts', '🌱', 'vegetables', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (23, '红薯', 'Sweet Potato', '🍠', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (24, '生姜', 'Ginger', '🫚', 'vegetables', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (30, '苹果', 'Apple', '🍎', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (31, '香蕉', 'Banana', '🍌', 'fruits', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (32, '橙子', 'Orange', '🍊', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (33, '葡萄', 'Grape', '🍇', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (34, '草莓', 'Strawberry', '🍓', 'fruits', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (35, '西瓜', 'Watermelon', '🍉', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (36, '芒果', 'Mango', '🥭', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (37, '猕猴桃', 'Kiwi', '🥝', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (38, '梨', 'Pear', '🍐', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (39, '桃子', 'Peach', '🍑', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (40, '樱桃', 'Cherry', '🍒', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (41, '蓝莓', 'Blueberry', '🫐', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (42, '柠檬', 'Lemon', '🍋', 'fruits', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (43, '柚子', 'Pomelo', '🍊', 'fruits', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (44, '火龙果', 'Dragon Fruit', '🍎', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (45, '菠萝', 'Pineapple', '🍍', 'fruits', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (46, '哈密瓜', 'Cantaloupe', '🍈', 'fruits', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (47, '荔枝', 'Lychee', '🍎', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (48, '石榴', 'Pomegranate', '🍎', 'fruits', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (49, '牛油果', 'Avocado', '🥑', 'fruits', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (60, '猪肉', 'Pork', '🥩', 'meat', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (61, '牛肉', 'Beef', '🥩', 'meat', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (62, '鸡胸肉', 'Chicken Breast', '🍗', 'meat', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (63, '鸡翅', 'Chicken Wings', '🍗', 'meat', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (64, '排骨', 'Ribs', '🍖', 'meat', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (65, '羊肉', 'Lamb', '🥩', 'meat', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (66, '五花肉', 'Pork Belly', '🥓', 'meat', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (67, '里脊肉', 'Tenderloin', '🥩', 'meat', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (68, '肉馅', 'Ground Meat', '🥩', 'meat', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (69, '鸡腿', 'Chicken Leg', '🍗', 'meat', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (70, '培根', 'Bacon', '🥓', 'meat', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (71, '香肠', 'Sausage', '🌭', 'meat', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (72, '鸭肉', 'Duck', '🦆', 'meat', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (73, '牛排', 'Steak', '🥩', 'meat', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (80, '虾', 'Shrimp', '🦐', 'seafood', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (81, '三文鱼', 'Salmon', '🐟', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (82, '鲈鱼', 'Sea Bass', '🐟', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (83, '带鱼', 'Hairtail', '🐟', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (84, '螃蟹', 'Crab', '🦀', 'seafood', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (85, '蛤蜊', 'Clam', '🐚', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (86, '鱿鱼', 'Squid', '🦑', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (87, '黄花鱼', 'Yellow Croaker', '🐟', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (88, '扇贝', 'Scallop', '🐚', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (89, '鲫鱼', 'Crucian Carp', '🐟', 'seafood', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (100, '牛奶', 'Milk', '🥛', 'dairy', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (101, '酸奶', 'Yogurt', '🥛', 'dairy', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (102, '鸡蛋', 'Eggs', '🥚', 'dairy', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (103, '奶酪', 'Cheese', '🧀', 'dairy', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (104, '黄油', 'Butter', '🧈', 'dairy', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (105, '奶油', 'Cream', '🥛', 'dairy', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (106, '豆浆', 'Soy Milk', '🥛', 'dairy', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (107, '豆腐', 'Tofu', '🧈', 'dairy', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (120, '大米', 'Rice', '🍚', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (121, '面条', 'Noodles', '🍜', 'staples', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (122, '面粉', 'Flour', '🌾', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (123, '食用油', 'Cooking Oil', '🫒', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (124, '挂面', 'Dried Noodles', '🍜', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (125, '燕麦', 'Oatmeal', '🌾', 'staples', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (126, '意大利面', 'Pasta', '🍝', 'staples', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (127, '面包', 'Bread', '🍞', 'staples', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (128, '馒头', 'Steamed Bun', '🍞', 'staples', 5, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (129, '粉丝', 'Vermicelli', '🍜', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (130, '糯米', 'Glutinous Rice', '🍚', 'staples', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (140, '酱油', 'Soy Sauce', '🧴', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (141, '醋', 'Vinegar', '🧴', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (142, '盐', 'Salt', '🧂', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (143, '白糖', 'Sugar', '🧂', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (144, '料酒', 'Cooking Wine', '🍶', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (145, '蚝油', 'Oyster Sauce', '🧴', 'condiments', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (146, '豆瓣酱', 'Doubanjiang', '🫙', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (147, '花椒', 'Sichuan Pepper', '🌶️', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (148, '辣椒粉', 'Chili Powder', '🌶️', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (149, '胡椒粉', 'Pepper', '🧂', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (150, '五香粉', 'Five Spice', '🧂', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (151, '番茄酱', 'Ketchup', '🧴', 'condiments', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (152, '芝麻油', 'Sesame Oil', '🫒', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (153, '老抽', 'Dark Soy Sauce', '🧴', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (154, '生抽', 'Light Soy Sauce', '🧴', 'condiments', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (155, '味精', 'MSG', '🧂', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (156, '鸡精', 'Chicken Powder', '🧂', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (157, '淀粉', 'Starch', '🌾', 'condiments', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (158, '八角', 'Star Anise', '⭐', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (159, '桂皮', 'Cinnamon', '🪵', 'condiments', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (170, '薯片', 'Chips', '🍟', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (171, '饼干', 'Cookies', '🍪', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (172, '巧克力', 'Chocolate', '🍫', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (173, '坚果', 'Nuts', '🥜', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (174, '矿泉水', 'Water', '💧', 'snacks', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (175, '可乐', 'Cola', '🥤', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (176, '果汁', 'Juice', '🧃', 'snacks', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (177, '咖啡', 'Coffee', '☕', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (178, '茶叶', 'Tea', '🍵', 'snacks', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (179, '蜂蜜', 'Honey', '🍯', 'snacks', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (180, '糖果', 'Candy', '🍬', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (181, '瓜子', 'Sunflower Seeds', '🌻', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (182, '啤酒', 'Beer', '🍺', 'snacks', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (183, '红酒', 'Wine', '🍷', 'snacks', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (190, '冷冻饺子', 'Frozen Dumplings', '🥟', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (191, '汤圆', 'Rice Balls', '🍡', 'frozen', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (192, '冰淇淋', 'Ice Cream', '🍦', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (193, '速冻蔬菜', 'Frozen Vegetables', '🥦', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (194, '冷冻披萨', 'Frozen Pizza', '🍕', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (195, '馄饨', 'Wonton', '🥟', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (196, '冷冻包子', 'Frozen Buns', '🍞', 'frozen', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (197, '速冻虾仁', 'Frozen Shrimp', '🦐', 'frozen', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (200, '纸巾', 'Tissue', '🧻', 'household', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (201, '卫生纸', 'Toilet Paper', '🧻', 'household', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (202, '洗洁精', 'Dish Soap', '🧴', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (203, '垃圾袋', 'Trash Bags', '🗑️', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (204, '保鲜膜', 'Plastic Wrap', '📦', 'household', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (205, '洗衣液', 'Laundry Detergent', '🧴', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (206, '柔顺剂', 'Fabric Softener', '🧴', 'household', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (207, '清洁剂', 'Cleaner', '🧹', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (208, '拖把', 'Mop', '🧹', 'household', 180, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (209, '海绵', 'Sponge', '🧽', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (210, '铝箔纸', 'Aluminum Foil', '📦', 'household', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (211, '厨房纸巾', 'Paper Towel', '🧻', 'household', 21, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (212, '洗碗布', 'Dish Cloth', '🧽', 'household', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (220, '洗发水', 'Shampoo', '🧴', 'personal', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (221, '牙膏', 'Toothpaste', '🪥', 'personal', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (222, '沐浴露', 'Body Wash', '🧴', 'personal', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (223, '面霜', 'Face Cream', '🧴', 'personal', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (224, '防晒霜', 'Sunscreen', '🧴', 'personal', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (225, '牙刷', 'Toothbrush', '🪥', 'personal', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (226, '棉签', 'Cotton Swabs', '🏥', 'personal', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (227, '护手霜', 'Hand Cream', '🧴', 'personal', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (228, '洗面奶', 'Face Wash', '🧴', 'personal', 45, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (229, '漱口水', 'Mouthwash', '🧴', 'personal', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (230, '卫生巾', 'Sanitary Pads', '🏥', 'personal', 30, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (231, '剃须刀', 'Razor Blades', '🪒', 'personal', 60, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (240, '尿布', 'Diapers', '👶', 'baby', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (241, '奶粉', 'Formula', '🍼', 'baby', 14, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (242, '湿巾', 'Baby Wipes', '🧻', 'baby', 10, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (243, '辅食', 'Baby Food', '🍼', 'baby', 7, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (244, '奶瓶', 'Baby Bottle', '🍼', 'baby', 90, 1);
INSERT INTO products (id, name, name_en, emoji, category, default_freq_days, is_system) VALUES (245, '婴儿洗衣液', 'Baby Detergent', '🧴', 'baby', 30, 1);
